name: Build & push Docker image to GHCR

on:
  push:
    branches: [ main ]     # main dalına her push’ta çalışsın

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write      # GHCR'a yükleyebilmek için

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.comfy-worker }}   # biraz önce eklediğin token

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
